In [3]:
import numpy as np
import multiprocessing
import time

In [4]:
# Initialize matrix A with random floating-point values
A = np.random.rand(200, 200).astype(np.float32)

# Initialize vector B with random floating-point values
B = np.random.rand(200).astype(np.float32)

# Printing A and B (optional)
print("Matrix A:")
print(A)
print("\nVector B:")
print(B)

Matrix A:
[[0.4714276  0.5892526  0.3973826  ... 0.4732418  0.19517124 0.36948878]
 [0.8387932  0.06810858 0.567876   ... 0.06313246 0.8289309  0.39525297]
 [0.09126715 0.22427519 0.43903133 ... 0.5456941  0.8457806  0.4963899 ]
 ...
 [0.36819062 0.3970589  0.23011333 ... 0.66938424 0.3623733  0.49153388]
 [0.9452132  0.3903168  0.63112956 ... 0.78890693 0.42107335 0.76685774]
 [0.6091455  0.1809672  0.7154402  ... 0.99266595 0.06875362 0.49657863]]

Vector B:
[2.4984398e-01 3.0609417e-01 2.4283521e-01 5.3557120e-02 8.7887657e-01
 2.3279659e-01 4.0323591e-01 3.9495373e-01 6.4964247e-01 1.1275277e-01
 5.9167612e-01 1.2816848e-01 7.7874285e-01 1.6978076e-01 2.6853591e-01
 8.5772657e-01 7.6699567e-01 9.1735616e-02 4.5461535e-01 1.0629357e-03
 3.2161942e-01 2.3226455e-01 1.8440101e-02 6.6115242e-01 7.7138484e-02
 3.5440061e-02 5.3382885e-01 6.2467849e-01 7.4202365e-01 9.6178544e-01
 4.9652490e-01 3.1721684e-01 4.1857746e-01 7.2792101e-01 6.0290521e-01
 4.3914902e-01 2.8710479e-01 8.6340195

In [5]:
# Function to perform matrix-vector multiplication
def mat_vec_multiply(matrix_row, vector):
    return np.dot(matrix_row, vector)

In [6]:
def apply_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.apply(mat_vec_multiply, args=(A, B))
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

In [7]:
def apply_async_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.apply_async(mat_vec_multiply, args=(A, B))
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result.get(), execution_time

In [8]:
def map_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.map(mat_vec_multiply, [A] * len(B), B)
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

In [9]:
def map_async_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.map_async(mat_vec_multiply, [A] * len(B), B)
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result.get(), execution_time

In [10]:
def starmap_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.starmap(mat_vec_multiply, [(A, b) for b in B])
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

In [11]:
def starmap_async_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.starmap_async(mat_vec_multiply, [(A, b) for b in B])
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result.get(), execution_time


In [12]:
def main():
 # Generate random matrix A and vector B

    # Measure execution time for each method
    result_apply, time_apply = apply_method(A, B)
    # result_apply_async, time_apply_async = apply_async_method(A, B)
    # result_map, time_map = map_method(A, B)
    # result_map_async, time_map_async = map_async_method(A, B)
    # result_starmap, time_starmap = starmap_method(A, B)
    # result_starmap_async, time_starmap_async = starmap_async_method(A, B)

    # Print results
    print(f"Method: apply, Execution Time: {time_apply:.6f} seconds")
    # print(f"Method: apply_async, Execution Time: {time_apply_async:.6f} seconds")
    # print(f"Method: map, Execution Time: {time_map:.6f} seconds")
    # print(f"Method: map_async, Execution Time: {time_map_async:.6f} seconds")
    # print(f"Method: starmap, Execution Time: {time_starmap:.6f} seconds")
    # print(f"Method: starmap_async, Execution Time: {time_starmap_async:.6f} seconds")
    
if __name__ == "__main__":
    main()