In [1]:
import numpy as np
import multiprocessing
import time

In [2]:
# Initialize matrix A with random floating-point values
A = np.random.rand(200, 200).astype(np.float32)

# Initialize vector B with random floating-point values
B = np.random.rand(200).astype(np.float32)

# Printing A and B (optional)
print("Matrix A:")
print(A)
print("\nVector B:")
print(B)

Matrix A:
[[0.4548763  0.6216911  0.50391525 ... 0.00369763 0.39375517 0.06718814]
 [0.31206653 0.29331502 0.9263065  ... 0.65614986 0.12358689 0.44600904]
 [0.29091084 0.31351155 0.22357476 ... 0.30011597 0.5337151  0.80260366]
 ...
 [0.86704206 0.9249799  0.6262949  ... 0.07470996 0.36723247 0.81213945]
 [0.81329954 0.38680884 0.76461536 ... 0.73545235 0.5887121  0.43404484]
 [0.53390807 0.83476394 0.58203906 ... 0.7946801  0.71955055 0.86713576]]

Vector B:
[0.70195705 0.8582592  0.63039845 0.6407655  0.0838889  0.49068233
 0.06188665 0.56804216 0.55312485 0.70143324 0.09529819 0.0068259
 0.28780523 0.377534   0.29577798 0.14743431 0.07699648 0.44986907
 0.8861802  0.43641105 0.69147766 0.5889099  0.40687627 0.50427306
 0.56893665 0.19742274 0.22145168 0.86135644 0.32386923 0.8211296
 0.47954488 0.46489078 0.56517833 0.9741643  0.44780457 0.94777465
 0.37993202 0.2521069  0.45698422 0.3285581  0.8780014  0.92533535
 0.16916123 0.3649087  0.8674782  0.41462225 0.8451864  0.93792206
 

In [3]:
# Function to perform matrix-vector multiplication
def mat_vec_multiply(matrix_row, vector):
    return np.dot(matrix_row, vector)

In [4]:
def apply_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.apply(mat_vec_multiply, args=(A, B))
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

In [5]:
def apply_async_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.apply_async(mat_vec_multiply, args=(A, B))
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result.get(), execution_time

In [6]:
def map_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.map(mat_vec_multiply, [A] * len(B), B)
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

In [7]:
def map_async_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.map_async(mat_vec_multiply, [A] * len(B), B)
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result.get(), execution_time

In [8]:
def starmap_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.starmap(mat_vec_multiply, [(A, b) for b in B])
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

In [9]:
def starmap_async_method(A, B):
    start_time = time.time()
    pool = multiprocessing.Pool()
    result = pool.starmap_async(mat_vec_multiply, [(A, b) for b in B])
    pool.close()
    pool.join()
    end_time = time.time()
    execution_time = end_time - start_time
    return result.get(), execution_time


In [10]:
def main():
 # Generate random matrix A and vector B

    print("Matrix A shape:", A.shape)
    print("Vector B shape:", B.shape)
    # Measure execution time for each method
    result_apply, time_apply = apply_method(A, B)
    # result_apply_async, time_apply_async = apply_async_method(A, B)
    # result_map, time_map = map_method(A, B)
    # result_map_async, time_map_async = map_async_method(A, B)
    # result_starmap, time_starmap = starmap_method(A, B)
    # result_starmap_async, time_starmap_async = starmap_async_method(A, B)

    # Print results
    print(f"Method: apply, Execution Time: {time_apply:.6f} seconds")
    # print(f"Method: apply_async, Execution Time: {time_apply_async:.6f} seconds")
    # print(f"Method: map, Execution Time: {time_map:.6f} seconds")
    # print(f"Method: map_async, Execution Time: {time_map_async:.6f} seconds")
    # print(f"Method: starmap, Execution Time: {time_starmap:.6f} seconds")
    # print(f"Method: starmap_async, Execution Time: {time_starmap_async:.6f} seconds")
    
if __name__ == "__main__":
    main()

Matrix A shape: (200, 200)
Vector B shape: (200,)
